language: python
dist: xenial
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip3 install pylint
  - pip3 install -r requirements.txt
script:
  - pylint cert_easy
  - pylint gen_ca.py
  - pylint gen_client.py
  - pylint simple_https_server.py
