language: python
dist: xenial
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.7-dev
  - 3.8-dev
  - nightly
install:
  - pip3 install pylint
  - pip3 install -r requirements.txt
script:
  - pylint --py3k --disable=print-statement cert_easy
  - pylint --disable=superfluous-parens cert_easy
  - pylint --py3k gen_ca.py
  - pylint gen_ca.py
  - pylint --py3k gen_client.py
  - pylint gen_client.py
  - pylint --py3k --disable=print-statement simple_https_server.py
  - pylint --disable=superfluous-parens simple_https_server.py
